/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        bg: {
          base:     'var(--color-bg-base)',
          surface:  'var(--color-bg-surface)',
          elevated: 'var(--color-bg-elevated)',
          hover:    'var(--color-bg-hover)',
          card:     'var(--bg-card)',
          glass:    'var(--bg-glass)',
        },
        accent: {
          DEFAULT: 'var(--color-accent-primary, #2dd4bf)',
          hover:   'var(--color-accent-hover, #5eead4)',
          subtle:  'var(--color-accent-subtle, rgba(45,212,191,0.14))',
          soft:    'var(--accent-muted)',
        },
        border: {
          DEFAULT: 'var(--color-border)',
          strong:  'var(--color-border-strong)',
          hover:   'var(--border-hover)',
          active:  'var(--border-active)',
        },
        text: {
          primary:   'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          muted:     'var(--text-muted)',
          faint:     'rgba(255,255,255,0.28)',
        },
        success: 'var(--color-success, #34d399)',
        warning: 'var(--color-warning, #fbbf24)',
        danger:  'var(--color-danger, #fb7185)',
        info:    'var(--color-info, #60a5fa)',
      },
      fontFamily: {
        display: ['Syne', 'Cairo', 'sans-serif'],
        body:    ['DM Sans', 'Cairo', 'sans-serif'],
        mono:    ['JetBrains Mono', 'monospace'],
      },
      animation: {
        'shimmer':       'shimmer 1.5s infinite',
        'slide-up':      'slideUp 200ms ease-out both',
        'slide-down':    'slideDown 220ms ease-out both',
        'slide-right':   'slideRight 250ms ease-out both',
        'fade-in':       'fadeIn 150ms ease-out both',
        'fade-up':       'fadeUp 300ms cubic-bezier(0.16, 1, 0.3, 1) both',
        'scale-in':      'scaleIn 180ms cubic-bezier(0.16, 1, 0.3, 1) both',
        'bounce-dot':    'bounceDot 0.4s ease',
        'pulse-glow':    'pulseGlow 2s ease-in-out infinite',
        'spin-slow':     'spin 3s linear infinite',
        'gradient-pan':  'gradientPan 8s ease infinite',
        'count-up':      'countUp 600ms cubic-bezier(0.16, 1, 0.3, 1) both',
        'tab-swap':      'tabSwap 220ms cubic-bezier(0.16, 1, 0.3, 1) both',
      },
      keyframes: {
        shimmer:    { '0%,100%': { opacity: '0.5' }, '50%': { opacity: '1' } },
        slideUp:    { from: { opacity: '0', transform: 'translateY(8px)' },  to: { opacity: '1', transform: 'translateY(0)' } },
        slideDown:  { from: { opacity: '0', transform: 'translateY(-8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        slideRight: { from: { opacity: '0', transform: 'translateX(-12px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        fadeIn:     { from: { opacity: '0' }, to: { opacity: '1' } },
        fadeUp:     { from: { opacity: '0', transform: 'translateY(14px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        scaleIn:    { from: { opacity: '0', transform: 'scale(0.95)' }, to: { opacity: '1', transform: 'scale(1)' } },
        bounceDot:  { '0%,100%': { transform: 'scale(1)' }, '50%': { transform: 'scale(1.4)' } },
        pulseGlow:  {
          '0%,100%': { boxShadow: '0 0 0 0 var(--focus-ring)' },
          '50%':     { boxShadow: '0 0 0 8px transparent' },
        },
        gradientPan: {
          '0%,100%': { backgroundPosition: '0% 50%' },
          '50%':     { backgroundPosition: '100% 50%' },
        },
        countUp: { from: { opacity: '0', transform: 'translateY(6px) scale(0.96)' }, to: { opacity: '1', transform: 'translateY(0) scale(1)' } },
        tabSwap: { from: { opacity: '0', transform: 'translateY(4px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
      },
      boxShadow: {
        sm:          'var(--shadow-sm)',
        md:          'var(--shadow-md)',
        lg:          'var(--shadow-lg)',
        card:        'var(--shadow-sm)',
        modal:       'var(--shadow-modal)',
        glow:        'var(--accent-glow)',
        'glow-soft': '0 0 30px var(--accent-muted)',
        'glow-lg':   'var(--logo-shadow)',
      },
      backgroundImage: {
        'accent-gradient':  'var(--gradient-accent)',
        'brand-gradient':   'var(--gradient-brand)',
        'surface-gradient': 'linear-gradient(180deg, var(--ambient-1) 0%, transparent 60%)',
      },
    },
  },
  plugins: [],
}
